CREATE SCHEMA IF NOT EXISTS cantina;

CREATE TABLE cantina.perfil (
    id_perfil INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(255),
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_perfil_nome_upper ON cantina.perfil (UPPER(nome));

CREATE OR REPLACE FUNCTION cantina.set_perfil_atualizado_em()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_perfil_atualizado_em
BEFORE UPDATE ON cantina.perfil
FOR EACH ROW
EXECUTE FUNCTION cantina.set_perfil_atualizado_em();

INSERT INTO cantina.perfil (nome, descricao)
VALUES
    ('ADMIN', 'Perfil administrativo com acesso completo ao sistema.'),
    ('USUARIO', 'Perfil padrao para usuarios da aplicacao.')
ON CONFLICT DO NOTHING;

COMMENT ON TABLE cantina.perfil IS 'Perfis disponiveis para classificacao e autorizacao de usuarios.';
COMMENT ON COLUMN cantina.perfil.id_perfil IS 'Identificador unico do perfil.';
COMMENT ON COLUMN cantina.perfil.nome IS 'Nome do perfil com unicidade case-insensitive.';
COMMENT ON COLUMN cantina.perfil.descricao IS 'Descricao funcional do perfil.';
COMMENT ON COLUMN cantina.perfil.criado_em IS 'Data e hora de criacao do perfil.';
COMMENT ON COLUMN cantina.perfil.atualizado_em IS 'Data e hora da ultima atualizacao do perfil.';
