CREATE TABLE stocklite.perfil (
    id_perfil INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(255),
    dta_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dta_update TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_perfil_nome_upper ON stocklite.perfil (UPPER(nome));

CREATE OR REPLACE FUNCTION stocklite.set_perfil_dta_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.dta_update = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_perfil_dta_update
BEFORE UPDATE ON stocklite.perfil
FOR EACH ROW
EXECUTE FUNCTION stocklite.set_perfil_dta_update();

COMMENT ON TABLE stocklite.perfil IS 'Perfis de acesso do sistema StockLite.';
COMMENT ON COLUMN stocklite.perfil.id_perfil IS 'Identificador unico do perfil.';
COMMENT ON COLUMN stocklite.perfil.nome IS 'Nome do perfil.';
COMMENT ON COLUMN stocklite.perfil.descricao IS 'Descricao do perfil.';
COMMENT ON COLUMN stocklite.perfil.dta_criacao IS 'Data e hora de criacao do registro.';
COMMENT ON COLUMN stocklite.perfil.dta_update IS 'Data e hora da ultima atualizacao do registro.';
