CREATE TABLE cantina.usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    perfil_fk INTEGER NOT NULL,
    CONSTRAINT fk_usuario_perfil
        FOREIGN KEY (perfil_fk) REFERENCES cantina.perfil(id_perfil) ON DELETE RESTRICT ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX uq_usuario_email_lower ON cantina.usuario (LOWER(email));
CREATE INDEX idx_usuario_perfil_fk ON cantina.usuario (perfil_fk);
CREATE INDEX idx_usuario_ativo ON cantina.usuario (ativo);

CREATE OR REPLACE FUNCTION cantina.set_usuario_atualizado_em()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_usuario_atualizado_em
BEFORE UPDATE ON cantina.usuario
FOR EACH ROW
EXECUTE FUNCTION cantina.set_usuario_atualizado_em();

COMMENT ON TABLE cantina.usuario IS 'Usuarios cadastrados na aplicacao cantina.';
COMMENT ON COLUMN cantina.usuario.id_usuario IS 'Identificador unico do usuario.';
COMMENT ON COLUMN cantina.usuario.nome IS 'Nome completo do usuario.';
COMMENT ON COLUMN cantina.usuario.email IS 'Endereco de e-mail do usuario com unicidade case-insensitive.';
COMMENT ON COLUMN cantina.usuario.senha_hash IS 'Hash da senha persistida para autenticacao.';
COMMENT ON COLUMN cantina.usuario.ativo IS 'Indica se o usuario esta ativo para acesso.';
COMMENT ON COLUMN cantina.usuario.criado_em IS 'Data e hora de criacao do usuario.';
COMMENT ON COLUMN cantina.usuario.atualizado_em IS 'Data e hora da ultima atualizacao do usuario.';
COMMENT ON COLUMN cantina.usuario.perfil_fk IS 'Perfil vinculado ao usuario.';
