CREATE TABLE stocklite.usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_fk INTEGER NOT NULL,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL,
    dta_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dta_update TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_perfil
        FOREIGN KEY (perfil_fk) REFERENCES stocklite.perfil(id_perfil) ON DELETE RESTRICT ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX uq_usuario_email_lower ON stocklite.usuario (LOWER(email));
CREATE INDEX idx_usuario_perfil_fk ON stocklite.usuario (perfil_fk);
CREATE INDEX idx_usuario_ativo ON stocklite.usuario (ativo);

CREATE OR REPLACE FUNCTION stocklite.set_usuario_dta_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.dta_update = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_usuario_dta_update
BEFORE UPDATE ON stocklite.usuario
FOR EACH ROW
EXECUTE FUNCTION stocklite.set_usuario_dta_update();

COMMENT ON TABLE stocklite.usuario IS 'Usuarios cadastrados no sistema StockLite.';
COMMENT ON COLUMN stocklite.usuario.id_usuario IS 'Identificador unico do usuario.';
COMMENT ON COLUMN stocklite.usuario.perfil_fk IS 'Perfil vinculado ao usuario.';
COMMENT ON COLUMN stocklite.usuario.nome IS 'Nome completo do usuario.';
COMMENT ON COLUMN stocklite.usuario.email IS 'Endereco de e-mail do usuario.';
COMMENT ON COLUMN stocklite.usuario.senha IS 'Senha do usuario persistida no banco.';
COMMENT ON COLUMN stocklite.usuario.ativo IS 'Indica se o usuario esta ativo.';
COMMENT ON COLUMN stocklite.usuario.dta_criacao IS 'Data e hora de criacao do registro.';
COMMENT ON COLUMN stocklite.usuario.dta_update IS 'Data e hora da ultima atualizacao do registro.';
