CREATE TABLE stocklite.produto (
    id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    preco NUMERIC(10, 2) NOT NULL,
    quantidade_estoque INTEGER NOT NULL,
    ativo BOOLEAN NOT NULL,
    dta_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dta_update TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_produto_ativo ON stocklite.produto (ativo);
CREATE INDEX idx_produto_nome ON stocklite.produto (nome);

CREATE OR REPLACE FUNCTION stocklite.set_produto_dta_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.dta_update = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_produto_dta_update
BEFORE UPDATE ON stocklite.produto
FOR EACH ROW
EXECUTE FUNCTION stocklite.set_produto_dta_update();

COMMENT ON TABLE stocklite.produto IS 'Produtos controlados no estoque.';
COMMENT ON COLUMN stocklite.produto.id_produto IS 'Identificador unico do produto.';
COMMENT ON COLUMN stocklite.produto.nome IS 'Nome do produto.';
COMMENT ON COLUMN stocklite.produto.descricao IS 'Descricao do produto.';
COMMENT ON COLUMN stocklite.produto.preco IS 'Preco unitario do produto.';
COMMENT ON COLUMN stocklite.produto.quantidade_estoque IS 'Quantidade disponivel em estoque.';
COMMENT ON COLUMN stocklite.produto.ativo IS 'Indica se o produto esta ativo.';
COMMENT ON COLUMN stocklite.produto.dta_criacao IS 'Data e hora de criacao do registro.';
COMMENT ON COLUMN stocklite.produto.dta_update IS 'Data e hora da ultima atualizacao do registro.';
