CREATE TABLE stocklite.movimentacao_estoque (
    id_movimentacao_estoque INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_fk INTEGER NOT NULL,
    usuario_fk INTEGER NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    quantidade INTEGER NOT NULL,
    data_movimentacao TIMESTAMP WITH TIME ZONE NOT NULL,
    observacao VARCHAR(255),
    dta_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dta_update TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movimentacao_produto
        FOREIGN KEY (produto_fk) REFERENCES stocklite.produto(id_produto) ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT fk_movimentacao_usuario
        FOREIGN KEY (usuario_fk) REFERENCES stocklite.usuario(id_usuario) ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT ck_movimentacao_tipo
        CHECK (tipo IN ('ENTRADA', 'SAIDA')),
    CONSTRAINT ck_movimentacao_quantidade
        CHECK (quantidade > 0)
);

CREATE INDEX idx_movimentacao_produto_fk ON stocklite.movimentacao_estoque (produto_fk);
CREATE INDEX idx_movimentacao_usuario_fk ON stocklite.movimentacao_estoque (usuario_fk);
CREATE INDEX idx_movimentacao_tipo ON stocklite.movimentacao_estoque (tipo);
CREATE INDEX idx_movimentacao_data ON stocklite.movimentacao_estoque (data_movimentacao);

CREATE OR REPLACE FUNCTION stocklite.set_movimentacao_dta_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.dta_update = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_movimentacao_dta_update
BEFORE UPDATE ON stocklite.movimentacao_estoque
FOR EACH ROW
EXECUTE FUNCTION stocklite.set_movimentacao_dta_update();

COMMENT ON TABLE stocklite.movimentacao_estoque IS 'Historico de entradas e saidas de estoque.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.id_movimentacao_estoque IS 'Identificador unico da movimentacao.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.produto_fk IS 'Produto vinculado a movimentacao.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.usuario_fk IS 'Usuario responsavel pela movimentacao.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.tipo IS 'Tipo da movimentacao: ENTRADA ou SAIDA.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.quantidade IS 'Quantidade movimentada.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.data_movimentacao IS 'Data e hora em que a movimentacao ocorreu.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.observacao IS 'Observacao complementar da movimentacao.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.dta_criacao IS 'Data e hora de criacao do registro.';
COMMENT ON COLUMN stocklite.movimentacao_estoque.dta_update IS 'Data e hora da ultima atualizacao do registro.';
